<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robotcar">

  <!-- Robot Dimensions -->
  <xacro:property name="body_length" value="0.68"/>
  <xacro:property name="body_width" value="0.33"/>
  <xacro:property name="body_height" value="0.30"/>
  <xacro:property name="wheel_radius" value="0.08"/>
  <xacro:property name="wheel_length" value="0.04"/> <!-- Assumed width of wheel -->
  <xacro:property name="wheel_separation_width" value="0.26"/>
  <xacro:property name="wheel_separation_length" value="0.405"/>

  <!-- Base Footprint -->
  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
  </joint>

  <!-- Base Link -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
      <material name="blue">
        <color rgba="0 0 1 1"/>
      </material>
      <origin xyz="0 0 ${body_height/2}" rpy="0 0 0"/>
    </visual>
    <collision>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
      <origin xyz="0 0 ${body_height/2}" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="10.0"/>
      <origin xyz="0 0 ${body_height/2}"/>
      <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
    </inertial>
  </link>

  <!-- IMU Link (Center of body) -->
  <link name="imu_link"/>
  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0 0 ${body_height/2}" rpy="0 0 0"/>
  </joint>

  <!-- Livox Link (Front Top Edge) -->
  <link name="livox_frame"/>
  <joint name="livox_joint" type="fixed">
    <parent link="base_link"/>
    <child link="livox_frame"/>
    <origin xyz="${body_length/2} 0 ${body_height}" rpy="0 -0.785398 0"/> <!-- 绕 Y 轴向上倾斜 45 度补偿物理向下角度，使scan水平 -->
  </joint>

  <!-- Wheels Macro -->
  <xacro:macro name="wheel" params="prefix x_offset y_offset">
    <link name="${prefix}_wheel_link">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
        <material name="black">
          <color rgba="0 0 0 1"/>
        </material>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      </collision>
      <inertial>
        <mass value="1.0"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
      </inertial>
    </link>

    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_wheel_link"/>
      <origin xyz="${x_offset} ${y_offset} 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <!-- Instantiate Wheels -->
  <xacro:wheel prefix="front_left" x_offset="${wheel_separation_length/2}" y_offset="${wheel_separation_width/2}"/>
  <xacro:wheel prefix="front_right" x_offset="${wheel_separation_length/2}" y_offset="-${wheel_separation_width/2}"/>
  <xacro:wheel prefix="rear_left" x_offset="-${wheel_separation_length/2}" y_offset="${wheel_separation_width/2}"/>
  <xacro:wheel prefix="rear_right" x_offset="-${wheel_separation_length/2}" y_offset="-${wheel_separation_width/2}"/>

  <!-- ROS2 Control -->
  <ros2_control name="RobotCar" type="system">
    <hardware>
      <plugin>robot_base/RobotCarHardwareInterface</plugin>
      <param name="serial_port_name">/dev/STM32</param>
      <param name="serial_baud_rate">115200</param>
      <param name="wheel_radius">${wheel_radius}</param>
      <param name="wheel_separation">${wheel_separation_width}</param>
    </hardware>
    
    <joint name="front_left_wheel_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="front_right_wheel_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="rear_left_wheel_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
    <joint name="rear_right_wheel_joint">
      <command_interface name="velocity"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
  </ros2_control>

</robot>
