#!/usr/bin/env python3
#
# Copyright 2023 6-robot.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Authors: Zhang Wanjie

import os
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.actions import IncludeLaunchDescription
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node, SetRemap
from launch.actions import GroupAction

def generate_launch_description():
    use_sim_time = LaunchConfiguration('use_sim_time', default='true')
    
    launch_file_dir = os.path.join(get_package_share_directory('wpr_simulation2'), 'launch')

    home_cmd = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(
            os.path.join(launch_file_dir, 'robocup_home.launch.py')
        )
    )

    behavior_tree = os.path.join(
        get_package_share_directory('wpr_simulation2'),
        'config',
        'behavior_tree.xml'
    )

    map_file = os.path.join(
        get_package_share_directory('wpr_simulation2'),
        'maps',
        'my_map.yaml'
    )
    
    nav_param_file = os.path.join(
        get_package_share_directory('wpr_simulation2'),
        'config',
        'nav2_params.yaml'
    )
    declare_params_file = DeclareLaunchArgument(
        'params_file',
        default_value=nav_param_file,
        description='Full path to Nav2 params YAML (controller_server config lives here)',
    )
    params_file = LaunchConfiguration('params_file')

    nav2_launch_dir = os.path.join(
        get_package_share_directory('nav2_bringup'), 
        'launch'
    )

    navigation_cmd = GroupAction(
        actions=[
            SetRemap(src='/cmd_vel', dst='/cmd_vel_engine'),
            IncludeLaunchDescription(
                PythonLaunchDescriptionSource([nav2_launch_dir, '/bringup_launch.py']),
                launch_arguments={
                    'map': map_file,
                    'use_sim_time': use_sim_time,
                    'params_file': params_file}.items(),
            )
        ]
    )

    waypoint_editor_dir = get_package_share_directory('waypoint_editor')
    rviz_config = os.path.join(waypoint_editor_dir, 'rviz', 'rviz_waypoint_editor.rviz')

    rviz_cmd = Node(
            package='rviz2',
            executable='rviz2',
            name='rviz2',
            arguments=['-d', rviz_config],
            # Force X11 backend to avoid Wayland/Xwayland GPU contention issues with Gazebo
            additional_env={'QT_QPA_PLATFORM': 'xcb'}
        )

    # Trajectory recorder node for path tracking analysis
    trajectory_recorder_cmd = Node(
        package='robot_route',
        executable='trajectory_recorder.py',
        name='trajectory_recorder',
        output='screen',
        parameters=[{'use_sim_time': True}]
    )

    # PP Controller waypoint file parameter
    # ====== 修改此处来加载不同的路径文件 ======
    # 留空则不自动加载，使用 /pp/load_path 服务动态加载
    # 示例: '/home/suja/voxel_ws/src/robot_app/waypoint_editor/wpfile/20231222_001500.json'
    waypoint_file_default = ''  # <-- 在此修改默认路径文件
    
    declare_waypoint_file = DeclareLaunchArgument(
        'waypoint_file',
        default_value=waypoint_file_default,
        description='Path to waypoint JSON file for PP Controller (generated by waypoint editor)'
    )
    waypoint_file = LaunchConfiguration('waypoint_file')

    # PP Controller auto_start parameter
    # ====== 设为 'true' 则启动时自动执行路径 ======
    declare_auto_start = DeclareLaunchArgument(
        'auto_start',
        default_value='false',  # <-- 默认不自动启动
        description='Auto-start path execution when waypoint_file is specified'
    )
    auto_start = LaunchConfiguration('auto_start')

    # PP Controller node (Industrial-grade path following)
    # pp_controller_cmd = Node(
    #     package='pp_controller',
    #     executable='pp_node',
    #     name='pp_controller',
    #     output='screen',
    #     parameters=[{
    #         'use_sim_time': True,
    #         'path_file': waypoint_file,
    #         'auto_start': auto_start,
    #         'pose_source': 'tf',
    #         'global_frame': 'map',
    #         'base_frame': 'base_link',
    #         'max_linear_vel': 0.3,
    #         'max_angular_vel': 1.0,
    #         'position_tolerance': 0.1,
    #         'angle_tolerance': 0.1,
    #         'obstacle_distance_threshold': 0.5,
    #     }]
    # )

    ld = LaunchDescription()

    # Add the commands to the launch description
    ld.add_action(declare_params_file)
    ld.add_action(declare_waypoint_file)
    ld.add_action(declare_auto_start)
    ld.add_action(home_cmd)
    ld.add_action(navigation_cmd)
    ld.add_action(rviz_cmd)
    ld.add_action(trajectory_recorder_cmd)
    # ld.add_action(pp_controller_cmd)

    return ld

    return ld
